#!/usr/bin/env python3
"""Regenerate a mod's sites.inc from a Mewgenics build.

A detour-style mod pins each call target by RVA plus the first 16 bytes found
there, and refuses to install if any one of them has moved. After a game update,
re-find the functions, put their new RVAs in MODS below, and rerun this.

Usage:  python make_sig.py [mod] [path-to-Mewgenics.exe]
        python make_sig.py all
Needs:  pip install capstone   (via find_gate.PE)
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from find_gate import PE, DEFAULT_EXE

N = 24     # must cover the longest prologue any mod steals

MODS = {
    "mewlinks": [
        ("INIT",         0x0e9ac0, "HouseCatStatus::init  - registers the panel's buttons"),
        ("REGISTER_BTN", 0x97c2b0, "MenuPanel::register_button(string, wstring, function<void()>)"),
        ("SHOW_CAT",     0x0ec7b0, "HouseCatStatus::show_cat(HouseCat*, bool clear_if_null)"),
        ("HOUSE_VIEW",   0x0ecc30, "HouseCatStatus::house_view  - [+0x88] is the zoomed room"),
        ("SINGLETON",    0x96b470, "ensure_singleton(holder, type_id)"),
        ("SOUND_CTX",    0x054500, "component -> object whose +0x2398 every button stores at +0x88"),
        ("RESOLVE_CAT",  0x0d7220, "CatRegistry::resolve(registry, u64 id) -> Cat*"),
        ("TREE_PASS",    0x17f7b0, "FamilyTreeHud highlight pass - hooked, to add buttons"),
        ("BUTTON",       0x97d590, "the Button constructor, which takes a clip pointer"),
        ("HOLDER_ARG",   0x96b3e0, "produces the Button constructor's second argument"),
        ("TREE_EXIT",    0x18ccd0, "the tree exit button's action; reads only [arg+8]"),
        ("STROKE",       0x9ffc40, "set the line style on a vector-graphics batch"),
        ("DRAW_CURVE",   0x17ddd0, "stroke one cubic bezier into the tree's batch"),
        ("MAP_HAS",      0x183db0, "is this cat id a node in the tree?"),
        ("MAP_FIND",     0x184d40, "look a cat id up in the tree's node map"),
    ],
    "mewbutch": [
        ("EVAL",     0x276600, "npc condition evaluator(self, condition, cat) -> bool"),
        ("REQ_ACT",  0x276940, "required_act(self)"),
        ("REQ_CHAP", 0x2769f0, "required_chapter(self)"),
        ("REQ_DIFF", 0x276ab0, "required_difficulty(self)"),
    ],
}


def main(mod, exe, out):
    data = open(exe, "rb").read()
    pe = PE(data)
    funcs = MODS[mod]
    lines = [
        "// Generated by tools/make_sig.py from %s." % os.path.basename(exe),
        "// Each entry pins one call target: RVA plus the first %d bytes found there." % N,
        "// A single mismatch aborts the whole install, so a rebuilt game is left alone",
        "// rather than hooked at a stale address.",
        "",
        "#define SITE_COUNT %d" % len(funcs),
        "#define SITE_SIGLEN %d" % N,
        "",
        "static const Site SITES[SITE_COUNT] = {",
    ]
    for name, rva, comment in funcs:
        off = pe.r2o(rva)
        if off is None:
            sys.exit("%s: rva %#x is not in any section" % (name, rva))
        f = pe.func_of(rva)
        if f is None or f[0] != rva:
            print("warning: %s at %#x is not a function start in .pdata" % (name, rva),
                  file=sys.stderr)
        body = ", ".join("0x%02x" % b for b in data[off:off + N])
        lines.append("    // %s" % comment)
        lines.append('    { "%s", 0x%06xu, { %s } },' % (name, rva, body))
    lines.append("};")
    lines.append("")
    for i, (name, _, _) in enumerate(funcs):
        lines.append("#define S_%-13s %d" % (name, i))
    open(out, "w").write(chr(10).join(lines) + chr(10))
    print("wrote %s (%d sites)" % (out, len(funcs)))


if __name__ == "__main__":
    args = [a for a in sys.argv[1:]]
    which = args.pop(0) if args and not args[0].lower().endswith(".exe") else "all"
    exe = args[0] if args else DEFAULT_EXE
    here = os.path.dirname(os.path.abspath(__file__))
    names = list(MODS) if which == "all" else [which]
    for name in names:
        if name not in MODS:
            sys.exit("unknown mod %r; known: %s" % (name, ", ".join(MODS)))
        main(name, exe, os.path.join(here, "..", name, "sites.inc"))
