#!/usr/bin/env python3
"""Regenerate mewlinks/sites.inc from a Mewgenics build.

The mod pins seven call targets by RVA plus the first 16 bytes found there, and
refuses to install if any one of them has moved. After a game update, re-find
the functions, put their new RVAs in FUNCS below, and rerun this.

Usage:  python make_sig.py [path-to-Mewgenics.exe]
Needs:  pip install capstone   (via find_gate.PE)
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from find_gate import PE, DEFAULT_EXE

N = 16
FUNCS = [
    ("INIT",         0x0e9ac0, "HouseCatStatus::init  - registers the panel's buttons"),
    ("REGISTER_BTN", 0x97c2b0, "MenuPanel::register_button(string, wstring, function<void()>)"),
    ("SHOW_CAT",     0x0ec7b0, "HouseCatStatus::show_cat(HouseCat*, bool clear_if_null)"),
    ("HOUSE_VIEW",   0x0ecc30, "HouseCatStatus::house_view  - [+0x88] is the zoomed room"),
    ("SINGLETON",    0x96b470, "ensure_singleton(holder, type_id)"),
    ("SOUND_CTX",    0x054500, "component -> object whose +0x2398 every button stores at +0x88"),
    ("RESOLVE_CAT",  0x0d7220, "CatRegistry::resolve(registry, u64 id) -> Cat*"),
]


def main(exe, out):
    data = open(exe, "rb").read()
    pe = PE(data)
    lines = [
        "// Generated by tools/make_sig.py from %s." % os.path.basename(exe),
        "// Each entry pins one call target: RVA plus the first %d bytes found there." % N,
        "// A single mismatch aborts the whole install, so a rebuilt game is left alone",
        "// rather than patched at a stale address.",
        "",
        "#define SITE_COUNT %d" % len(FUNCS),
        "#define SITE_SIGLEN %d" % N,
        "",
        "static const Site SITES[SITE_COUNT] = {",
    ]
    for name, rva, comment in FUNCS:
        off = pe.r2o(rva)
        if off is None:
            sys.exit("%s: rva %#x is not in any section" % (name, rva))
        if pe.func_of(rva) is None or pe.func_of(rva)[0] != rva:
            print("warning: %#x is not the start of a function in .pdata" % rva,
                  file=sys.stderr)
        body = ", ".join("0x%02x" % b for b in data[off:off + N])
        lines.append("    // %s" % comment)
        lines.append('    { "%s", 0x%06xu, { %s } },' % (name, rva, body))
    lines.append("};")
    lines.append("")
    for i, (name, _, _) in enumerate(FUNCS):
        lines.append("#define S_%-13s %d" % (name, i))
    open(out, "w").write("\n".join(lines) + "\n")
    print("wrote %s (%d sites)" % (out, len(FUNCS)))


if __name__ == "__main__":
    exe = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_EXE
    here = os.path.dirname(os.path.abspath(__file__))
    main(exe, os.path.join(here, "..", "mewlinks", "sites.inc"))
